# SPDX-License-Identifier: MIT

set(CMAKE_SYSTEM_NAME avr32)
set(CMAKE_SYSTEM_PROCESSOR avr32)
set(CMAKE_CROSSCOMPILING ON)

set(CMAKE_C_COMPILER avr32-gcc)
set(CMAKE_CXX_COMPILER avr32-g++)
set(CMAKE_ASM_COMPILER avr32-gcc)
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
set(CMAKE_COMPILER_WORKS)
#set(CMAKE_CROSSCOMPILING_EMULATOR "qemu-aarch64-static;-L;/usr/aarch64-linux-gnu/")
